# Generated by Django 2.2.5 on 2019-09-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('result', models.IntegerField()),
            ],
        ),
    ]
