# Generated by Django 2.2.5 on 2019-11-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='result',
            field=models.CharField(max_length=20),
        ),
    ]
